### PR TITLE
Brave Rewards Settings CSS

### PR DESCRIPTION
**Pull request by rossmoody**
Resolves: https://github.com/brave/brave-ui/issues/403
Addresses: https://github.com/brave/brave-browser/issues/4035

Core PR: https://github.com/brave/brave-core/pull/2173#pullrequestreview-223479167

I built this branch in Core. The screenshots are [attached to the main issue. ](https://github.com/brave/brave-browser/issues/4035)

### CODE REVIEW

**Comment by rossmoody** [comment]
@ryanml this one is ready for your review. I built the Core version of it and everything looked pretty good but I'm a little out of the loop on the mobile front and though it looked ok in storybook I figured there might be some remaining elements in the android repo to consider.

**Comment by ryanml** [comment]
@rossmoody can you rebase and then create a `now` link to the storybook for this PR?

**Comment by rossmoody** [comment]
@ryanml ready: https://brave-ui-lvqs8cyq8.now.sh

**Comment by ryanml** [comment]
@rossmoody once this is good to merge, can you squash up commits? Maybe down to 2 or 3 meaningful portions. Thanks!

**Pull request merged**
