### PR TITLE
Welcome dark theme

### PR DESCRIPTION
**Pull request by rossmoody**
Addresses: https://github.com/brave/brave-browser/issues/4657
Addresses: https://github.com/brave/brave-browser/issues/3911

Now: https://brave-ui-en211eort.now.sh

## Before

image

## After

image

image

### CODE REVIEW

**Comment by cezaraugusto** [comment]
also on hover it almost disappears

**Comment by rossmoody** [comment]
@cezaraugusto This one is worth another look. I think I was working on the button PR at the same time but now that it's merged that button seems to be ok. 

This is what I'm seeing: 
image

I think implementing this on core side with a theme provider is a little out of my depth at the moment. Any way you could help with that?

**Comment by imptrx** [comment]
we are currently waiting on some updates on the brave-core side to enable dark mode work on our internal pages. I can help with the core PR once it's ready as I'll be doing analogous work for NTP

**Comment by petemill** [comment]
We'll need to import this to Brave-Core directly since Welome-specific UI is no longer used from this repo as of https://github.com/brave/brave-core/pull/2896

**Comment by imptrx** [comment]
I'll address all the changes here in https://github.com/brave/brave-core/pull/2909 😃

**Pull request merged**
