### PR TITLE
brand new NoScript option

### PR DESCRIPTION
**Pull request by cezaraugusto**
now link: https://brave-ui-2q580wb8f.now.sh/?path=/story/feature-components-shields--enabled

### CODE REVIEW

**Comment by cezaraugusto** [comment]
@karenkliu could you check again? I updated the `now` link https://brave-ui-2q580wb8f.now.sh/?path=/story/feature-components-shields--enabled

**Comment by karenkliu** [comment]
Hi @cezaraugusto, thanks for getting these changes in! Most of the feedback was addressed; except for:

scripts QA 3
There should still be a primary and secondary background color on Shields dark theme but it seems that your latest update replaced both backgrounds with the new color.

**Comment by cezaraugusto** [comment]
thanks for reviewing, updated: https://brave-ui-pgt1s0adm.now.sh

**Comment by karenkliu** [comment]
Looks good to go now :thumbsup:

**Pull request merged**
