### PR TITLE
sanitize social media links in tipping banner

### LINKED ISSUE #466: Tipping banner should sanitize social media links
Hackerone issue: https://hackerone.com/reports/577426
Discussion thread in Slack: https://bravesoftware.slack.com/archives/G2KN13Z8C/p1557962234053000
Publishers issue: https://github.com/brave-intl/publishers/issues/1891

### PR DESCRIPTION
**Pull request by diracdeltas**
fix #466

## Test plan
1. go to https://www.nate.blue/ (it may not load; that's fine)
2. click rewards icon to send a tip
3. no social icons should appear

##### Link / storybook path to visual changes
- No visual changes

## Integration
- [ ] Does this contain changes to src/components or src/
  - [ ] Will you publish to npm immediately after this PR, or wait until sometime in the future?
  - [ ] Incompatible API change to something existing _(major version increase)_
  - [ ] Adding new backwards-compatible functionality? _(minor version increase)_
  - [ ] Fixing a bug backwards-compatibly? _(patch version increase)_
  
- [ ] Does this contain changes to src/features for brave-core?
  - [ ] Are there non backwards-compatible changes required for brave-core? **Do not merge until brave-core PR is approvable.** Link to brave-core PR:
  - [ ] Will you create brave-core PR to update to this commit after it is merged?
  - [ ] Wants uplift to brave-core feature branch?
     - When uplift-approved, merge to brave-core-0.VV.x feature branch
     - Create additional brave-core PRs for each feature branch to update commit

### CODE REVIEW

**Comment by diracdeltas** [comment]
@dlipeles i'd rather just normalize item.url since it's used directly as an href attribute - so for instance if `item.url` is `www.twitch.tv/test`, i would normalize that to `https://twitch.tv/test` before it's set as an href.

**Comment by diracdeltas** [comment]
> @dlipeles i'd rather just normalize item.url since it's used directly as an href attribute - so for instance if `item.url` is `www.twitch.tv/test`, i would normalize that to `https://twitch.tv/test` before it's set as an href.

this can be done here in this PR

**Comment by diracdeltas** [comment]
updated the implementation and added unit tests which passed locally. i tried to do the manual test plan but nate.blue doesn't show up as verified in Brave dev

**Comment by NejcZdovc** [comment]
@diracdeltas Travis is failing, can you please check why https://travis-ci.org/brave/brave-ui/jobs/533611667

**Comment by petemill** [comment]
I don’t want to delay this since this implementation will work, but do you think a better place for this kind of logic is in the (c++) layer that fetched the data and provides it to the ui layer, rather than inside a UI display component? @nejczdovc @diracdeltas

**Comment by diracdeltas** [comment]
> will work, but do you think a better place for this kind of logic is in the (c++) layer that fetched the data and provides it to the ui layer

I'm a bit mixed on this. I think logically it makes sense in the C++ layer, but it is easier to ensure these URLs are always sanitized if the sanitization checks happens right before the href is set. I guess it's a question of whether it's acceptable for the UI layer to blindly trust that the input from the C++ layer is sanitized.

 @NejcZdovc thanks, i'll work on fixing those

**Comment by petemill** [comment]
> I'm a bit mixed on this. I think logically it makes sense in the C++ layer, but it is easier to ensure these URLs are always sanitized if the sanitization checks happens right before the href is set. I guess it's a question of whether it's acceptable for the UI layer to blindly trust that the input from the C++ layer is sanitized.

Thanks - in that case @diracdeltas I would suggest if keeping it in the UI layer (the typescript), that it would be better to put it in the data-retrieval part, just after the URLs come back from c++ and are added to the state. As you have it now, it is in the render layer, which will re-run often and unnecessarily, and we want to avoid this performance-problematic pattern.

**Comment by diracdeltas** [comment]
@petemill can you point me at where that would be? i assume it's in brave-core?

**Comment by diracdeltas** [comment]
closing in favor of b-c PR

**Pull request closed without merging**
