### PR TITLE
Mobile siteBanner

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: #254 

Note: A new component was not created for this, as layout did not really need to change, just styles.

Now Link: https://brave-ui-awdllyyigp.now.sh
(Use the mobile inspector and view at **Feature Components > Rewards > Concepts > Mobile > Site Banner**)

In Action:

screen shot 2018-11-02 at 11 52 04 pm

### CODE REVIEW

**Comment by jenn-rhim** [comment]
@ryanml looks great! Maybe the site initial can be smaller. Other than that, I think it’s ready for a spin. Btw, looks like the string update has not made it in here yet— still seeing ‘donation’ which should be ‘Tip’.

**Comment by ryanml** [comment]
@jenn-rhim : Site initial has been updated to be smaller (new link is: https://brave-ui-awdllyyigp.now.sh/, preview in PR updated as well)

https://github.com/brave/brave-ui/issues/256

I just made this issue regarding the string update, as we'd be removing/modifying translated strings, I'd rather this be accomplished in a separate issue. Thanks!

**Comment by cezaraugusto** [comment]
@ryanml please rebase

**Comment by ryanml** [comment]
@cezaraugusto rebased

**Comment by ryanml** [comment]
Here is this PR overlaying master: (I think the overlay above may be mismatched)

As you can see, the site banner portion on desktop should be unmodified. The only modifications I made explicitly on desktop as well were to the "Send my Donation" button, as it was crooked on desktop. I think we should keep this modification.

I see the spacing is a bit different on this PR for donation amount buttons, that I can fix back. wdyt about keeping the modifications to the send button? cc: @jenn-rhim @NejcZdovc 

screen shot 2018-11-08 at 11 15 39 am

**Pull request merged**
