### PR TITLE
Added test ids for toggle and rewards maintoggle

### PR DESCRIPTION
**Pull request by jasonrsadler**
Adding test-ids for rewards testing.

### CODE REVIEW

**Comment by jasonrsadler** [comment]
Done. Thanks.

**Comment by ryanml** [comment]
@jasonrsadler can you rebase with master? (this should fix Travis) then we should be good to go

**Comment by jasonrsadler** [comment]
This is still in progress.

**Comment by ryanml** [comment]
@jasonrsadler why did I not see the label in front of me :D thanks

**Comment by jasonrsadler** [comment]
one is a prop and one is the rendered attribute

**Comment by petemill** [comment]
Should we just allow all data-* props to pass through from component to the
first rendered element of the component?

**Comment by jasonrsadler** [comment]
In some cases, for my tests on `brave-core`, I need to grab an id for a toggle, which isn't available at the component from within core. 

(or maybe I didn't understand the question)

**Comment by ryanml** [comment]
@jasonrsadler I mean that in `src/components/formControls/toggle/index.tsx` it is `data-test-id` as a rendered att, and in `src/features/rewards/box/index.tsx` it is `datatestid` as a rendered att.

**Comment by jasonrsadler** [comment]
in `src/features/rewards/box/index.tsx` it is datatestid because it is passed as a prop down to `toggle`

**Comment by jasonrsadler** [comment]
Agree. Change prop name to `testId`

**Pull request merged**
